---
language: "python"
python:
  - "3.7"

install:
  - "pip install -r requirements.txt"

before_script:
  - "pylint *.py"
  - "black --line-length 80 --check *.py"
  - "exabgp conf.txt --test"

script:
  - "exabgp conf.txt &"
  - "pytest --verbose test_api.py"
